### ISSUE TITLE
Reading Ecore model

### ISSUE THREAD

**Issue by jdupouy** [emfjson/ecore.js#8]
I'm trying to read an Ecore model
```
var Ecore = require('ecore');
var fs = require('fs');

var resourceSet = Ecore.ResourceSet.create();
var resource = resourceSet.create({uri : '/machin'});
var metamodel = fs.readFileSync('MyMetaModel.ecore', 'utf8');

resource.parse(metamodel, Ecore.XMI);
```
and I get this message
```
<?xml version="1.0" encoding="UTF-8"?>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.Ecore.JSON.parse (/home/julien/tmp/test/node_modules/ecore/dist/ecore.js:1679:25)
    at Ecore.Resource.Ecore.EClass.create.eOperations._ [as parse] (/home/julien/tmp/test/node_modules/ecore/dist/ecore.js:1970:32)
    at Object.<anonymous> (/home/julien/tmp/test/test.js:183:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
```
It seems that the parser is not taking into account the `Ecore.XMI` parameter.

Am I doing something wrong ? Any suggestion ?

**Comment by ghillairet** [comment]
Try this import instead:

```js
var Ecore = require('ecore/dist/ecore.xmi');
```

**Comment by jdupouy** [comment]
Thanks a lot.

I finally figured it out myself by looking at your tests scenari.

BTW really nice library !
